# Generated by Django 3.0.8 on 2020-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200729_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brief',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
